---
plexurl: "https://downloads.plex.tv/plex-media-server/1.7.3.3937-70f781325/plexmediaserver_1.7.3.3937-70f781325_amd64.deb"
plextarget: "/tmp/plex1.7.3.3937.deb"

users:
  vmansible: [1]
  vmldev16: [1,2]
  vmdevplex: [1,3]
  vmdevpar2: [1,2]
  vmdevsonarr: [1,3]

userlist:
  1:
    username: "{{ lookup('file', '../secretfiles/1/name.txt') }}"
    userid: "{{ lookup('file', '../secretfiles/1/userid.txt') }}"
    password: "{{ lookup('file', '../secretfiles/1/password.txt') }}"
    keyfilelocation: "{{ '../secretfiles/1' }}"
    groups: "sudo"
    usernumber: 1
  2:
    username: "{{ lookup('file', '../secretfiles/2/name.txt') }}"
    userid: "{{ lookup('file', '../secretfiles/2/userid.txt') }}"
    password: "{{ lookup('file', '../secretfiles/2/password.txt') }}"
    keyfilelocation: "{{ '../secretfiles/2' }}"
    groups: "sudo"
    usernumber: 2
  3:
    username: "{{ lookup('file', '../secretfiles/3/name.txt') }}"
    userid: "{{ lookup('file', '../secretfiles/3/userid.txt') }}"
    password: "{{ lookup('file', '../secretfiles/3/password.txt') }}"
    keyfilelocation: "{{ '../secretfiles/3' }}"
    groups: "sudo"
    usernumber: 3

