---
- name: pause for 20 seconds
  pause:
    seconds: 20

- name: waiting for server to come back
  become: no
  local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
