---
- name: "Installing required software"
  become: true
  apt: pkg={{ item }} state=installed
  with_items:
  - nfs-common

- name: create /nas folder
  become: true
  file:
    path: /nas
    state: directory
    owner: "{{ userlist[1].username }}"
    group: "{{ userlist[1].username }}"
    mode: 0777
    

- name: "Mount {{ description }}"
  become: true
  mount:
    path: "{{ path }}"
    src: "{{ src }}"
    fstype: nfs
    opts: soft,intr,rsize=8192,wsize=8192
    state: mounted

