---
- name: Check for previous install of myzsh
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  stat: path="~/.myzsh/completions/_myzsh"
  register: p

- name: Install myzsh if it's not installed
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  git:
    repo: 'https://github.com/myzsh/myzsh'
    dest: "~/.myzsh"
    key_file: "~/.ssh/id_rsa"
    accept_hostkey: true
  when: 
  - not p.stat.exists
  
