---
- include: install-common-pkgs.yml

- hosts: needsramdisk
  become: true
  roles:
  - ramdisk


- hosts: needsnfsraspbian
  become: true
  roles:
  - nfsraspbian

- hosts: needsnfsmedia
  become: true
  roles:
  - nfsmedia

- include: addusers.yml

- hosts: all
  become: true
  tasks:
  - name: Upgrade all packages in RedHat-based machines
    when: ansible_os_family == "Redhat"
    yum: name=* state=latest

  - name: Upgrade all packages in Debian-based machines
    when: ansible_os_family == "Debian"
    apt: upgrade=dist update_cache=yes

  - name: Reboot required
    shell: ( /bin/sleep 5 ; shutdown -r now "Ansible updates triggered" ) &
          removes=/var/run/reboot-required
    async: 30
    poll: 0
    ignore_errors: true
    notify:
      - waiting for server to come back

  handlers:
  - name: waiting for server to come back
    become: no
    local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
