---
- hosts: devops
  become: true
  gather_facts: true
  roles:
  - devops-install
  - nfsmedia
  - nfscode
  - ramdisk
  - logfolder
  tags:
  - devops


# final thing
- hosts: devops
  become: true
  gather_facts: false
  roles:
  - reboot-os
