---
- hosts: all
  become: true
  tasks:
  - name: Upgrade all packages in RedHat-based machines
    when: ansible_os_family == "Redhat"
    yum: name=* state=latest

  - name: Upgrade all packages in Debian-based machines
    when: ansible_os_family == "Debian"
    apt: upgrade=dist update_cache=yes

  - name: Checking if Reboot is required
    raw: "([ -f /var/run/reboot-required ] && echo 'Reboot' || echo 'NotFound')"
    register: result
    changed_when: false
  
  - name: Rebooting if needed
    shell: "/bin/sleep 3 && shutdown -r now 'Ansible updates triggered'"
    async: 1
    poll: 0
    when: result.stdout == "\r\nReboot\r\n"
    notify:
      - pause for 20 seconds
      - waiting for server to come back

  handlers:
  - name: pause for 20 seconds
    pause:
      seconds: 20

  - name: waiting for server to come back
    become: no
    local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300

