---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - name: Install Python 2
    raw: test -e /usr/bin/python || (dpkg --configure -a && apt -y update && apt install -y python-minimal)
    register: output
    changed_when: false

- hosts: all
  become: true
  gather_facts: true
  roles:
  - update-os
  - reboot-os
