---
# Copies the id keys to the user folders.  It uses the userlist dictionary
#   found in group_vars folder for the data and the users dictionary
#   to determine what users are added to a specific server.

- name: Create user .ssh folder
  become: true
  file:
    path: "/home/{{ userlist[outer_item]['username'] }}/.ssh" 
    state: directory
    owner: "{{ userlist[outer_item]['username'] }}"
    group: "{{ userlist[outer_item]['username'] }}"
  when:
  - outer_item in users[targethost]

- name: Copy SSH Files
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ userlist[outer_item]['username'] }}"
    group: "{{ userlist[outer_item]['username'] }}"
    force: true
  with_items:
  - {src: "{{ userlist[outer_item]['keyfilelocation'] }}/.ssh/", dest: "/home/{{ userlist[outer_item]['username'] }}/.ssh/", mode: "0700"}
  when:
  - outer_item in users[targethost]
  tags:
  - setup-user
  - travis-skip


- name: Set SSH Files permissions
  become: true
  ignore_errors: yes
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: "{{ userlist[outer_item]['username'] }}"
    group: "{{ userlist[outer_item]['username'] }}"
    force: true
  with_items:
  - {path: "/home/{{ userlist[outer_item]['username'] }}/.ssh", mode: "0700"}
  - {path: "/home/{{ userlist[outer_item]['username'] }}/.ssh/id_rsa", mode: "0400"}
  - {path: "/home/{{ userlist[outer_item]['username'] }}/.ssh/id_rsa.pub", mode: "0400"}
  - {path: "/home/{{ userlist[outer_item]['username'] }}/.ssh/authorized_keys", mode: "0600"}
  - {path: "/home/{{ userlist[outer_item]['username'] }}/.ssh/20170707_key_pair.pem", mode: "0400"}
  when:
  - outer_item in users[targethost]
  tags:
  - setup-user
  - travis-skip

- name: ensure env-var file exists
  become: true
  ignore_errors: yes
  copy:
    content: ""
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ userlist[outer_item]['username'] }}"
    group: "{{ userlist[outer_item]['username'] }}"
    force: no
  with_items:
  - {dest: "/home/{{ userlist[outer_item]['username'] }}/.ssh/env-var", mode: "0400"}
  when:
  - outer_item in users[targethost]
  tags:
  - setup-user
  - travis-skip
