---
# Copies the id keys to the user folders.  It uses the userlist dictionary
#   found in group_vars folder for the data and the users dictionary
#   to determine what users are added to a specific server.

- name: Create user .ssh folder
  become: true
  file:
    path: "/home/{{ userlist[outer_item]['username'] }}/.ssh" 
    state: directory
    owner: "{{ userlist[outer_item]['username'] }}"
    group: "{{ userlist[outer_item]['username'] }}"
  when:
  - outer_item in users[targethost]

- name: Copy SSH Files
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ userlist[outer_item]['username'] }}"
    group: "{{ userlist[outer_item]['username'] }}"
    force: true
  with_items:
  - {src: "{{ userlist[outer_item]['keyfilelocation'] }}/id_rsa", dest: "/home/{{ userlist[outer_item]['username'] }}/.ssh", mode: "0400"}
  - {src: "{{ userlist[outer_item]['keyfilelocation'] }}/id_rsa.pub", dest: "/home/{{ userlist[outer_item]['username'] }}/.ssh", mode: "0400"}
  - {src: "{{ userlist[outer_item]['keyfilelocation'] }}/authorized_keys", dest: "/home/{{ userlist[outer_item]['username'] }}/.ssh", mode: "0600"}
  when:
  - outer_item in users[targethost]
  tags:
  - setup-user
  - travis-skip
