---

- name: "Installing required software"
  apt: pkg={{ item }} state=installed
  with_items:
  - nfs-common

- name: "Mount Raspbian"
  mount:
    path: /nas/raspbian
    src: 192.168.13.11:/datapool/raspbian/cp/crashplan/programming
    fstype: nfs
    opts: soft,intr,rsize=8192,wsize=8192
    state: mounted
