---
- name: Call ohmyzsh-install one user at a time.
  include_role:
    name: ohmyzsh-install
    usernumber: "{{ outer_item }}"
  with_items:
  - "{{ outer_item }}"
  when:
  - outer_item in users[targethost]

- name: Call call powerline-fonts one user at a time.
  include_role:
    name: powerline-fonts
    usernumber: "{{ outer_item }}"
  with_items:
  - "{{ outer_item }}"
  when:
  - outer_item in users[targethost]


