---
# requires files per user, each in their own folder (1/, 2/, etc):  nameone.txt, userid.txt, password.txt, id_rsa, id_rsa.pub
# Reminder how to create password for the password.txt:  mkpasswd --method=sha-512

- name: Add User
  become: true
  vars:
    userName: "{{ lookup('file', '..//secretfiles/{{ usernumber }}/name.txt') }}"
    userId: "{{ lookup('file', '../secretfiles/{{ usernumber }}/userid.txt') }}"
    userPw: "{{ lookup('file', '../secretfiles/{{ usernumber }}/password.txt') }}"
  user:
    name: "{{ userName }}"
    groups: adm,sudo
    password: "{{ userPw }}"
    shell: /usr/bin/zsh
    uid: "{{ userId }}"
    state: present
    
- name: Create user .ssh folder
  become: true
  vars:
    userName: "{{ lookup('file', '../secretfiles/{{ usernumber }}/name.txt') }}"
    userHomeFolder: "/home/{{ userName }}" 
  file:
    path: "{{ userHomeFolder }}/.ssh" 
    state: directory
    owner: "{{ userName }}"
    group: "{{ userName }}"

- name: Copy SSH files
  become: true
  vars:
    userName: "{{ lookup('file', '../../../../secretfiles/{{ usernumber }}/name.txt') }}"
    userId: "{{ lookup('file', '../../../../secretfiles/{{ usernumber }}/userid.txt') }}"
    userPw: "{{ lookup('file', '../secretfiles/{{ usernumber }}/password.txt') }}"
    userHomeFolder: "/home/{{ userName }}"
    userSshPrivKeySrc: "../secretfiles/{{ usernumber }}/id_rsa"
    userSshPrivKeyDest: "{{ userHomeFolder }}/.ssh/id_rsa"
    userSshPubKeySrc: "../../../../secretfiles/{{ usernumber }}/id_rsa.pub"
    userSshPubKeyDest: "{{ userHomeFolder }}/.ssh/id_rsa.pub"
  copy:
    src: "{{item.src}}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ userName }}"
    group: "{{ userName }}"
    force: true
  with_items:
  - {src: "{{ userSshPubKeySrc }}", dest: "{{userSshPubKeyDest}}", mode: "0400"}
  - {src: "{{ userSshPrivKeySrc }}", dest: "{{userSshPrivKeyDest}}", mode: "0400"}
