---
# requires files per user, each in their own folder (1/, 2/, etc):  nameone.txt, userid.txt, password.txt, id_rsa, id_rsa.pub
# Reminder how to create password for the password.txt:  mkpasswd --method=sha-512

- name: Add User
  become: true
  vars:
    userName: "{{ lookup('file', '..//secretfiles/{{ usernumber }}/name.txt') }}"
    userId: "{{ lookup('file', '../secretfiles/{{ usernumber }}/userid.txt') }}"
    userPw: "{{ lookup('file', '../secretfiles/{{ usernumber }}/password.txt') }}"
  user:
    name: "{{ userName }}"
    groups: adm,sudo
    password: "{{ userPw }}"
    shell: /usr/bin/zsh
    uid: "{{ userId }}"
    state: present
    
- name: Create user .ssh folder
  become: true
  vars:
    userName: "{{ lookup('file', '../secretfiles/{{ usernumber }}/name.txt') }}"
    userHomeFolder: "/home/{{ userName }}" 
  file:
    path: "{{ userHomeFolder }}/.ssh" 
    state: directory
    owner: "{{ userName }}"
    group: "{{ userName }}"

- name: Copy SSH files
  become: true
  vars:
    userName: "{{ lookup('file', '../../../../secretfiles/{{ usernumber }}/name.txt') }}"
    userId: "{{ lookup('file', '../../../../secretfiles/{{ usernumber }}/userid.txt') }}"
    userPw: "{{ lookup('file', '../secretfiles/{{ usernumber }}/password.txt') }}"
    userHomeFolder: "/home/{{ userName }}"
    userLocalSrcFolder: "../secretfiles/{{ usernumber }}/"
    userRemoteDestFolder: "{{ userHomeFolder }}/.ssh/"
  copy:
    src: "{{item.src}}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ userName }}"
    group: "{{ userName }}"
    force: true
  with_items:
  - {src: "{{ userLocalSrcFolder }}id_rsa", dest: "{{ userRemoteDestFolder }}", mode: "0400"}
  - {src: "{{ userLocalSrcFolder }}id_rsa.pub", dest: "{{ userRemoteDestFolder }}", mode: "0400"}
  - {src: "{{ userLocalSrcFolder }}authorized_keys", dest: "{{ userRemoteDestFolder }}", mode: "0600"}

- name: Check for previous install of Oh My Zsh
  remote_user: "{{ lookup('file', '..//secretfiles/{{ usernumber }}/name.txt') }}"
  vars:
    userName: "{{ lookup('file', '../../../../secretfiles/{{ usernumber }}/name.txt') }}"
  stat: path="/home/{{ userName }}/.oh-my-zsh/oh-my-zsh.sh"
  register: p

- name: Install oh my zsh
  remote_user: "{{ lookup('file', '..//secretfiles/{{ usernumber }}/name.txt') }}"
  shell: "sh -c \"$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\""
  when: not p.stat.exists
