---
- name: "Installing Common Apps"
  become: true
  apt: pkg={{ item }} state=installed
  with_items:
  - nfs-common
  - par2

- name: Check if mount point exists
  stat: path=/nas/offline
  register: check_path

- name: Create offline media folder
  become: true
  file: 
    path: /nas/offline
    state: directory
    owner: "{{ userlist[2]['username'] }}"
    group: "{{ userlist[2]['username'] }}"
    mode: 0777
  when:
  - not check_path.stat.exists

- name: "Mount offline Media"
  become: true
  mount:
    path: /nas/offline/
    src: 192.168.13.11:/datapool/media/Video/z_offline
    fstype: nfs
    opts: soft,intr,rsize=8192,wsize=8192
    state: mounted

- name: Call docker role to install docker
  include_role:
    name: docker

- name: git download the docker-par2 project
  become: false
  remote_user: "{{ userlist[2]['username'] }}"
  git:
    repo: "{{ item.repoSrc }}"
    dest: "{{ item.repoDest }}"
    key_file: "{{ userlist[2]['username'] }}/.ssh/id_rsa"
    accept_hostkey: true
  with_items:
  - {repoSrc: "git@github.com:energyvault462/docker-par2.git", repoDest: "/home/{{ userlist[2]['username'] }}/docker-par2"}

