---
- name: Check if oh-my-zsh is installed
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  stat: path="/home/{{ userlist[usernumber].username }}/.oh-my-zsh/oh-my-zsh.sh"
  register: p

- name: Install oh-my-zsh if it's not installed
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  shell: "sh -c \"$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\""
  when: not p.stat.exists
