---
- name: "Installing python-pip and fontconfig"
  apt: pkg={{ apt_item }} state=installed
  with_items:
  - python-pip
  - fontconfig
  loop_control:
    loop_var: apt_item 

- name: "oh-my-zsh: pip install powerline"
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  shell: "pip install --user git+git://github.com/Lokaltog/powerline"

- name: "oh-my-zsh: add to ~/.profile"
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  blockinfile:
    path: ~/.profile
    block: |
      if [ -d "$HOME/.local/bin" ]; then
        PATH="$HOME/.local/bin:$PATH"
      fi

- name: "oh-my-zsh - DL PowerlineSymbols.otf"
  become: yes
  become_user: "{{ userlist[usernumber].username }}"  
  get_url:
    url: "https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf"
    dest: "~"

- name: "oh-my-zsh - DL 10-powerline-symbols"
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  get_url:
    url: "https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf"
    dest: "~"

- name: checking if the file 1 exists
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  stat:      
    path: ~/PowerlineSymbols.otf
  register: one_result

- name: "oh-my-zsh: mkdir ~/.config/fontconfig/conf.d/"
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  file:
    path: ~/.fonts/
    state: directory
    owner: "{{ userlist[usernumber].username }}"
    group: "{{ userlist[usernumber].username }}"
    mode: 0775
    recurse: yes


- name: moving file 1
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  command: "mv ~/PowerlineSymbols.otf ~/.fonts/"
  when: one_result.stat.exists == True

- name: "oh-my-zsh: fc-cache"
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  shell: "fc-cache -vf ~/.fonts"
  when: one_result.stat.exists == True

- name: "oh-my-zsh: mkdir ~/.config/fontconfig/conf.d/"
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  file:
    path: ~/.config/fontconfig/conf.d/
    state: directory
    owner: "{{ userlist[usernumber].username }}"
    group: "{{ userlist[usernumber].username }}"
    mode: 0775
    recurse: yes

- name: "checking if the file 10-powerline-symbols.conf exists"
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  stat:      
    path: "~/10-powerline-symbols.conf"
  register: two_result

- name: "moving file 10-powerline-symbols.conf"
  become: yes
  become_user: "{{ userlist[usernumber].username }}"
  command: "mv ~/10-powerline-symbols.conf ~/.config/fontconfig/conf.d/"
  when: two_result.stat.exists == True
