---
- name: Create link to ansible folder
  become: false
  file:
    src: /nas/ansible/
    dest: "/home/{{ userlist[1].username }}/ansible"
    owner: "{{ userlist[1].username }}"
    group: "{{ userlist[1].username }}"
    state: link

- name: Create link to secretfiles folder
  become: false
  file:
    src: "/home/{{ userlist[1].username }}/secretfiles"
    dest: "/nas/secretfiles"
    owner: "{{ userlist[1].username }}"
    group: "{{ userlist[1].username }}"
    state: link

- name: git clone ansible
  become: false
  remote_user: "{{  userlist[1].username }}"
  git:
    repo: 'git@github.com:energyvault462/ansible.git'
    dest: "/home/{{  userlist[1].username }}/ansible"
    key_file: "/home/{{  userlist[1].username }}/.ssh/id_rsa"
    accept_hostkey: true

- name: git clone secret files backup
  become: false
  remote_user: "{{  userlist[1].username }}"
  git:
    repo: 'git@bitbucket.org:energyvault462/secretfiles-backup.git'
    dest: "/home/{{  userlist[1].username }}/secretfiles-backup"
    key_file: "/home/{{  userlist[1].username }}/.ssh/id_rsa"
    accept_hostkey: true
