---

- name: "Installing required software"
  apt: pkg={{ item }} state=installed
  with_items:
  - nfs-common

- name: "Mount code"
  mount:
    path: /nas/code
    src: 192.168.13.11:/datapool/code/cp/crashplan
    fstype: nfs
    opts: soft,intr,rsize=8192,wsize=8192
    state: mounted

- name: Create link to code folder
  become: true
  file:
    src: /nas/code/
    dest: "/home/{{ userlist[item]['username'] }}/code"
    owner: "{{ userlist[item]['username'] }}"
    group: "{{ userlist[item]['username'] }}"
    state: link
  with_items:
  - "{{ users[ansible_hostname] }}"
