---
- name: Download plex deb
  get_url: url=https://downloads.plex.tv/plex-media-server/0.9.11.16.958-80f1748/plexmediaserver_0.9.11.16.958-80f1748_amd64.deb dest=/tmp/plex.deb

- name: Install plex
  apt: deb=/tmp/plex.deb
  sudo: yes

- name: Make sure that plex is started
  service: name=plexmediaserver state=started
