---
- name: git clone projects
  become: true
  become_user: "{{  userlist[usernum]['username'] }}"
  git:
    repo: 'git@github.com:energyvault462/docker-brent.git'
    dest: "~/projects/docker-brent"
    key_file: "~/.ssh/id_rsa"
    accept_hostkey: true
