---

- name: git dotfiles for the users.
  become: false
  remote_user: "{{ lookup('file', '..//secretfiles/{{ usernumber }}/name.txt') }}"
  vars:
    userName: "{{ lookup('file', '..//secretfiles/{{ usernumber }}/name.txt') }}"
    repoSrc: 'https://github.com/energyvault462/dotfiles.git'
    repoDest: "/home/{{ userName  }}/dotfiles"
  git:
    repo: "{{ repoSrc }}"
    dest: "{{ repoDest }}"
    key_file: "/home/{{ userName }}/.ssh/id_rsa"
    accept_hostkey: true
  notify:
  -  Creates links for the dot files

- name: Find dot files in home directory that need to be deleted
  become: false
  remote_user: "{{ lookup('file', '..//secretfiles/{{ usernumber }}/name.txt') }}"
  find:
    paths: "~"
    patterns: ".bashrc,.gitconfig,.zshrc"
    hidden: true
    recurse: false
    file_type: file
  register: find_results

- name: remove files
  become: false
  remote_user: "{{ lookup('file', '..//secretfiles/{{ usernumber }}/name.txt') }}"
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ find_results.files }}"
  when: find_results.matched > 0
  notify:
  - Creates links for the dot files

- name: Find linked files in ~/
  become: false
  remote_user: "{{ lookup('file', '..//secretfiles/{{ usernumber }}/name.txt') }}"
  find:
    paths: "~"
    patterns: ".bashrc,.gitconfig,.zshrc"
    hidden: true
    recurse: false
    file_type: link
  register: find_link_results

- name: remove files (will delete if > 0 are found)
  become: false
  remote_user: "{{ lookup('file', '..//secretfiles/{{ usernumber }}/name.txt') }}"
  command: "echo not enough link files found"
  when: find_link_results.matched < 3
  notify:
  - Creates links for the dot files
