---
# Clones git repos for each user.  It uses the userlist dictionary
#   found in group_vars folder for the data and the users dictionary
#   to determine what users are added to a specific server.

- block:
  - name: git dotfiles for users.
    become: false
    remote_user: "{{ userlist[outer_item]['username'] }}"
    git:
      repo: "{{ item.repoSrc }}"
      dest: "{{ item.repoDest }}"
      key_file: "{{ userlist[outer_item]['username'] }}/.ssh/id_rsa"
      accept_hostkey: true
    with_items:
    - {repoSrc: "git@github.com:energyvault462/dotfiles.git", repoDest: "/home/{{ userlist[outer_item]['username'] }}/dotfiles"}
    when:
    - outer_item in users[targethost]
    tags:
    - setup-user
